# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

constantroute <- function(inflow, record, pad_n, nseg) {
    .Call(`_hydrostreamer_constantroute`, inflow, record, pad_n, nseg)
}

delineatecpp <- function(seeds, basID, drdir, delbas, nx, ny) {
    .Call(`_hydrostreamer_delineatecpp`, seeds, basID, drdir, delbas, nx, ny)
}

